name: smart_aquarium_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.4.0-163.0.dev <4.0.0'

dependencies:
    audioplayers: ^5.2.1
    firebase_core: ^2.25.4
    firebase_database: ^10.4.6
    flutter:
        sdk: flutter
    flutter_switch: ^0.3.2
    shared_preferences: ^2.2.2
    sleek_circular_slider: ^2.0.1
    time_picker_spinner_pop_up: ^1.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    flutter_launcher_icons: '^0.13.1'

flutter_launcher_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/images/sac_icon.png'
    min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
    uses-material-design: true
